services:
  backend:
    image: ssm.backend
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend/:/app
      - ./data/:/data
      - ./.home:/root
    environment:
      PATH: '/root/.local/bin:/usr/local/bin:/usr/bin:/bin'
      PIP_ROOT_USER_ACTION: ignore
    ports:
      - 8000:8000
    command: uv run fastapi dev --host 0.0.0.0 --port 8000 server.py

  frontend:
    image: ssm.frontend
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend/:/app
      - ./.home:/root
    environment:
      PATH: '/root/.local/bin:/usr/local/bin:/usr/bin:/bin'
    ports:
      - 3000:3000
    command: pnpm dev --host 0.0.0.0 --port 3000
